{
    'name': 'Inrim Controllo Accessi',
    'version': '17.0.1.0.0',
    'description': "Inrim Controllo Accessi",
    'depends': ['inrim_anagrafiche'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/ir_config_parameter_data.xml',
        'data/ca_anag_avanzamento_rich_data.xml',
        'data/ca_anag_tipologie_istanze_data.xml',
        'data/ca_punto_accesso_data.xml',
        'data/ca_tag_lettore_data.xml',
        'data/ca_settore_ente_data.xml',
        'data/ca_anag_servizi_data.xml',
        'wizard/ca_sposta_punto_accesso_views.xml',
        'wizard/ca_aggiungi_movimento_accesso_views.xml',
        'views/ca_tag_lettore_views.xml',
        'views/ca_punto_accesso_persona_views.xml',
        'views/ca_punto_accesso_views.xml',
        'views/ca_anag_registro_accesso_views.xml',
        'views/ca_log_integrazione_lettori_views.xml',
        'views/ca_settore_ente_views.xml',
        'views/ca_anag_servizi_views.xml',
        'views/ca_anag_tipologie_istanze_views.xml',
        'views/ca_anag_avanzamento_rich_views.xml',
        'views/ca_richiesta_servizi_persona_views.xml',
        'views/ca_richiesta_accesso_persona_views.xml',
        'views/ca_richiesta_accesso_views.xml',
        'views/menus.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
}