{
    'name': 'Inrim Controllo Accessi Custom',
    'version': '17.0.1.0.0',
    'description': "Inrim Controllo Accessi Custom",
    "author": "Alessio Gerace - Inrim",
    "website": "https://github.com/INRIM",
    'depends': [
        'inrim_iam_user_ldap',
        'inrim_controllo_accessi_api'
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/ir_config_parameter_data.xml',
        'data/ca_anag_servizi_data.xml',
        'data/ca_settore_ente_data.xml',
        'data/ca_categoria_richiesta_data.xml',
        'data/ca_categoria_tipo_richiesta_data.xml',
        'data/ca_anag_avanzamento_rich_data.xml',
        'data/ca_anag_tipologie_istanze_data.xml',
        'views/ca_categoria_richiesta_views.xml',
        'views/ca_categoria_tipo_richiesta_views.xml',
        'views/ente_azienda_views.xml',
        'views/ca_persona_views.xml',
        'views/ca_settore_ente_views.xml',
        'views/ca_anag_servizi_views.xml',
        'views/ca_anag_tipologie_istanze_views.xml',
        'views/ca_anag_avanzamento_rich_views.xml',
        'views/ca_richiesta_servizi_persona_views.xml',
        'views/ca_richiesta_accesso_persona_views.xml',
        'views/ca_richiesta_accesso_views.xml',
        'views/menu.xml',
    ],
    'demo': [
        'demo/ca_ente_azienza_demo.xml',
    ],
    'installable': True,
    'application': True,
}
