from . import ca_persona
from . import ca_tipo_persona
from . import ca_documento
from . import ca_ente_azienda
from . import ca_lettore
from . import ca_tag
from . import ca_tag_persona
from . import ca_spazio
from . import ca_codice_locale
from . import ca_righe_persona
from . import ca_registro_accesso
from . import ca_righe_accesso