from . import ca_punto_accesso_persona
from . import ca_tag_lettore
from . import ca_punto_accesso
from . import ca_anag_registro_accesso
from . import ca_log_integrazione_lettori
from . import ca_settore_ente
from . import ca_anag_servizi
from . import ca_anag_tipologie_istanze
from . import ca_anag_avanzamento_rich
from . import ca_richiesta_servizi_persona
from . import ca_richiesta_accesso_persona
from . import ca_richiesta_accesso