from . import auth
from . import persona
from . import richiesta_registro_accesso_sede
from . import tipo_ente_azienda
from . import ente_azienda
from . import spazio
from . import img_documento
from . import lettore
from . import documento