name: tests
env:
  REPO_NAME: Addons-Controllo-Accessi
  ODOO_RC: odoo.cfg
  ADDONS_PATH: /opt/odoo/addons,/mnt/server-auth,/mnt/Addons-Controllo-Accessi
  TESTTAGS: inrim
  OE_VER: "17.0"

on:
  pull_request:
    branches:
      - "17.0*"
  push:
    branches:
      - "17.0"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check Modules on ${{ github.event_name }}
    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.REPO_NAME }}
          persist-credentials: false
          fetch-depth: 1
      - uses: actions/checkout@v4
        with:
          repository: INRIM/Odoo-Qa
          path: oqa
          ref: ${{ env.OE_VER }}
          token: ${{ secrets.CA_TOKEN }}
          fetch-depth: 1
      - uses: actions/checkout@v4
        with:
          repository: https://github.com/OCA/server-auth.git
          path: oqa
          ref: server-auth
          fetch-depth: 1
      - run: pip install -r server-auth/requirements.txt
      - run: pip install -r server-auth/test-requirements.txt
      - name: Install dependencies
        run: ${PWD}/oqa/bin/install_deps.sh
      - name: Init Data
        run: ${PWD}/oqa/bin/init_repo.sh
      - name: Tests
        run: docker run --rm  -v ${PWD}/run_tests.sh:/mnt/tests/runtests.sh -v ${PWD}/${{ env.REPO_NAME }}:/mnt/${{ env.REPO_NAME }} -v ${PWD}/${ODOO_RC}:/etc/odoo/odoo.conf --network=host odoo:${{ env.OE_VER }} /mnt/tests/runtests.sh
